# -*- coding: utf-8 -*-
"""
Created on Fri Jan 29 15:11:02 2016

@author: rjohnson26

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""
# part 1: generate triangle numbers

z = []
k = 0
j = 1
while len(z) < 500:    
        z = []
        x = (sum(range(0,j)))
        for i in range(1,int(round(x**0.5,0))):
            if x%i == 0:
                z.append(i)
                z.append(x/i)
        j+=1
        if len(z) > k:
            k = len(z)
            print k, x



# part 2: count number of divisors
#x = []
#i = 1
#while len[x] < 500:
#    for i in range(1,)